version: '3'

services:
  postgresDatabase:
    image: postgres
    container_name: postgresdb
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - .:/usr/share/postgres
